#!/bin/bash
# cleanup-env-files.sh
# Script to clean up environment-specific files and synchronize environment variables

# Print colored output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${BLUE}=== Cleaning up environment files and synchronizing variables ===${NC}"

# Navigate to root directory
cd "$(dirname "$0")/.." || exit

# Check if root .env exists, create if it doesn't
if [ ! -f ".env" ] && [ -f ".env.development" ]; then
  echo -e "${YELLOW}Creating .env file from .env.development...${NC}"
  cp .env.development .env
  echo -e "${GREEN}Created .env file${NC}"
elif [ ! -f ".env" ]; then
  echo -e "${RED}No .env or .env.development file found. Please create an .env file first.${NC}"
  echo -e "${YELLOW}You can copy .env.example to .env to get started.${NC}"
  exit 1
fi

# Create/update mobile app .env with only EXPO_PUBLIC_ variables
echo -e "${YELLOW}Updating mobile app .env file...${NC}"
mkdir -p apps/mobile
grep "EXPO_PUBLIC_" .env > apps/mobile/.env.tmp
if [ -s apps/mobile/.env.tmp ]; then
  # Add header comment
  echo "# Generated by cleanup-env-files.sh" > apps/mobile/.env
  echo "# Mobile app environment variables - only public variables exposed to client" >> apps/mobile/.env
  cat apps/mobile/.env.tmp >> apps/mobile/.env
  rm apps/mobile/.env.tmp
  echo -e "${GREEN}Successfully updated apps/mobile/.env${NC}"
else
  echo -e "${YELLOW}No EXPO_PUBLIC_ variables found in root .env file${NC}"
  rm apps/mobile/.env.tmp
  exit 1
fi

# Clean up any environment-specific files that might cause confusion
echo -e "${YELLOW}Cleaning up environment-specific files...${NC}"

# Find all environment-specific files to remove (recursively)
echo -e "${YELLOW}Searching for environment-specific files...${NC}"
env_files=$(find . -name ".env.*" -not -name ".env.example" -not -path "*/node_modules/*")

if [ -z "$env_files" ]; then
  echo -e "${GREEN}No environment-specific files found.${NC}"
else
  echo -e "${YELLOW}Found the following environment-specific files:${NC}"
  echo "$env_files"
  
  # Remove each file
  for file in $env_files; do
    echo -e "${YELLOW}Removing $file${NC}"
    rm "$file"
  done
  
  echo -e "${GREEN}Removed all environment-specific files.${NC}"
fi

echo -e "${GREEN}=== Environment cleanup complete! ===${NC}"
echo -e "${BLUE}Local development now uses:${NC}"
echo -e "${BLUE}- Root level: .env${NC}"
echo -e "${BLUE}- Mobile app: apps/mobile/.env${NC}"